 2018-03-30 03:01:34,847 [P8080/D2/T31] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-03-30 03:01:34,847 [P8080/D2/T31] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-03-30 03:01:34,847 [P8080/D2/T31] INFO  Umbraco.Core.PluginManager - Resolving [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController
 2018-03-30 03:01:34,847 [P8080/D2/T31] INFO  Umbraco.Core.PluginManager - Resolved [Umbraco.Web.Trees.TreeAttribute]Umbraco.Web.Trees.TreeController (took 0ms)
 2018-03-30 03:01:34,911 [P8080/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-03-30 03:01:34,911 [P8080/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-03-30 03:01:34,911 [P8080/D2/T12] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IAction
 2018-03-30 03:01:34,911 [P8080/D2/T12] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IAction (took 1ms)
 2018-03-30 03:01:38,256 [P8080/D2/T12] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username ik@ik.dk from IP address ::1
 2018-03-30 03:01:38,256 [P8080/D2/T12] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: ik@ik.dk logged in from IP address ::1
 2018-03-30 03:03:12,886 [P8080/D2/T43] ERROR dashboardUtilities.FeedProxy - Exception occurred
System.Net.WebException: The remote name could not be resolved: 'umbraco.tv'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at dashboardUtilities.FeedProxy.Page_Load(Object sender, EventArgs e)
 2018-03-30 03:03:12,926 [P8080/D2/T43] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
 2018-03-30 03:03:12,926 [P8080/D2/T43] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
 2018-03-30 03:03:12,926 [P8080/D2/T43] INFO  Umbraco.Core.PluginManager - Resolving Umbraco.Web.HealthCheck.HealthCheck
 2018-03-30 03:03:12,930 [P8080/D2/T43] INFO  Umbraco.Core.PluginManager - Resolved Umbraco.Web.HealthCheck.HealthCheck (took 1ms)
 2018-03-30 03:21:13,114 [P8080/D2/T70] INFO  Umbraco.Core.Logging.OwinLogger - Event Id: 0, state: User logged will be logged out due to timeout: ik@ik.dk, IP Address: ::1
 2018-03-30 09:27:53,773 [P8080/D2/T67] INFO  umbraco.BusinessLogic.Log - Log scrubbed.  Removed all items older than 2018-03-29 09:27:53
 2018-03-30 19:25:59,737 [P8080/D2/T46] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: Login attempt succeeded for username ik@ik.dk from IP address ::1
 2018-03-30 19:25:59,737 [P8080/D2/T46] INFO  Umbraco.Core.Security.BackOfficeSignInManager - Event Id: 0, state: User: ik@ik.dk logged in from IP address ::1
 2018-03-30 19:45:33,267 [P8080/D2/T52] INFO  Umbraco.Core.Logging.OwinLogger - Event Id: 0, state: User logged will be logged out due to timeout: ik@ik.dk, IP Address: ::1
 2018-03-30 20:00:15,771 [P8080/D2/T56] INFO  Umbraco.Core.Security.UmbracoMembershipProviderBase - Login attempt succeeded for username obama from IP address ::1
